config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated do
    root "users#index"
  end
  resources :category_transactions
  resources :users, only: [:index]
  resources :categories, only: [:index, :show, :new, :create] do
    resources :transactions, only: [ :new, :show, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'categories#index', as: "home"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_transactions, foreign_key: :category_id, dependent: :destroy
  has_many :transactions, through: :category_transactions, source: :my_transaction

  belongs_to :user

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @category_transactions = @category.transactions.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.create(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <nav class='navbar'>
    <ul class="signup-ul">
      <li>
        <a href="/categories" class="back-arrow"><i class="fa fa-arrow-left"></i></a>
      </li>
      <li>
        <h2>New Category</h2>
      </li>
      <li class="actions">
        <%= form.submit "Add", class: "submit-signup" %>
      </li>
    </ul>
  </nav>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-container">
  <div>
    
    <%= form.text_field :name, placeholder: "Name", class: "input-field" %>
  </div>

  <div>   
    <%= form.text_field :icon, placeholder: "Enter URL", class: "input-field" %>
  </div>

</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<nav class='navbar'>
  <ul class="signup-ul">
    <li>
      <a href="/categories" class="back-arrow"><i class="fa fa-arrow-left"></i></a>
    </li>
    <li>
      <h2>CATEGORIES</h2>
    </li>
    <li class="actions">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "submit-signup" %>
    </li>
  </ul>
</nav>
<p style="color: green"><%= notice %></p>
<div id="card-container">
 <% if @categories.any? %>

  <% @categories.each do |category| %>
    <ul class="card-ul">
      <div class="image-description-container">
      <li class="card">
        <img src="<%= category.icon %>" class="icon-img" alt="icon of <%= category.name %>", width="100px", height="80px" />
      </li>
      <li class="card">
        <p class="transaction-name"><%= link_to category.name, category %></p><br>
        <p class="transaction-date"><%= category.created_at.strftime("%d-%b-%Y")  %></p>
      </li>
      </div>
      <li class="card">
        <p class="transaction-amount">$<%= category.transactions.sum(:amount) %> </p>
      </li>
    </ul>

      <%# <%= link_to "Show this category", category %>
  <% end %>
  <% else %>
  <p class="none">There Are No Categories. Please Add Category</p>
  <% end %>
<%= link_to "New category", new_category_path, class:"add-transaction" %>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

<br>

<div class="devise-shared-links">
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="transactions-container">
<nav class='navbar'>
  <ul class="signup-ul">
    <li>
      <a href="/categories" class="back-arrow"><i class="fa fa-arrow-left"></i></a>
    </li>
    <li>
      <h2>TRANSACTIONS</h2>
    </li>
    <li class="actions">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "submit-signup" %>
    </li>
  </ul>
</nav>
<p style="color: green"><%= notice %></p>
<div class="card-container">
 <% if @category.transactions.any? %>

  <% @category.transactions.each do |t| %>
    <ul class="card-ul">
      <div class="image-description-container">
      <li class="card">
        <img src="<%= @category.icon %>" class="icon-img" alt="icon of <%= @category.name %>", width="100px", height="80px" />
      </li>
      <li class="card">
        <p class="transaction-name"><%= t.name%></p><br>
        <p class="transaction-date"><%= t.created_at.strftime("%d-%b-%Y")  %></p>
      </li>
      </div>
      <li class="card">
        <p class="transaction-amount">$<%= t.amount %></p>
      </li>
    </ul>
  <% end %>
  <% else %>
    <p class="none">No Transactions Yet. Please Add A Transaction</p>
  <% end %>
</div>


<%# <%= @category.transactions.sum(:amount) %> 
</div>
<%= link_to "Add transaction",  "/categories/#{@category.id}/transactions/new", class:"add-transaction" %>