config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated do
    root "users#index"
  end
  resources :category_transactions
  resources :users, only: [:index]
  resources :categories, only: [:index, :show, :new, :create] do
    resources :transactions, only: [ :new, :show, :create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'categories#index', as: "home"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, foreign_key: :user_id, dependent: :destroy
  has_many :transactions, foreign_key: :user_id, dependent: :destroy

  validates :name, presence: true
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @category = Category.find(params[:category_id])
    @transaction = @category.transactions.create(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to "/categories/#{@category.id}", notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.permit(:name, :amount, :user_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with url: "/categories/#{@category.id}/transactions" do |form| %>
    <nav class='navbar'>
    <ul class="signup-ul">
      <li>
        <a href="/categories/:id" class="back-arrow"><i class="fa fa-arrow-left"></i></a>
      </li>
      <li>
        <h2>New Transaction</h2>
      </li>
      <li class="actions">
        <%= form.submit "Add", class: "submit-signup" %>
      </li>
    </ul>
  </nav>
  
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= form.text_field :name,required: true, class: "input-field", placeholder: "Name" %><br>
  </div>
  <div class="field">
    <%=form.text_field :category, value:@category.name, class: "input-field" %><br>
  </div>
  <div class="field">
    <%= form.number_field :amount ,  class:"p-2 form-control" , required: true, placeholder: 'Amount', class: "input-field", min: 1, id:"amount"%><br>
  </div>

<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Name:</strong>
    <%= transaction.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

app/views/transactions/new.html.erb
<%= render "form", transaction: @transaction %>

<br>

<div class="devise-shared-links">
  <%= link_to "Back to transactions", "/" %>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>
<%= @transaction.category_ids %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>